package com.vinod.docsch.db.entity;

// Generated Nov 29, 2013 12:59:05 PM by Hibernate Tools 4.0.0

import java.util.HashSet;
import java.util.Set;

import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.GenerationType;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.JoinTable;
import javax.persistence.OneToMany;
import javax.persistence.Table;




/**
 * TblRole generated by hbm2java
 */

@Entity  
@Table(name="tbl_role")

public class TblRole implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy=GenerationType.AUTO)
	@Column(name = "roleId")
	private Integer roleId;
	
	@Column(name="roleName")
	private String roleName;
	
	
	@OneToMany(cascade=CascadeType.ALL)  
    @JoinTable(name="tbl_user_role",   
        joinColumns = {@JoinColumn(name="roleId", referencedColumnName="roleId")},  
        inverseJoinColumns = {@JoinColumn(name="userId", referencedColumnName="userId")}  
    )  
	private Set<TblUser> tblUserRoles = new HashSet<TblUser>();

	public TblRole() {
	}

	public TblRole(String roleName, Set<TblUser> tblUserRoles) {
		this.roleName = roleName;
		this.tblUserRoles = tblUserRoles;
	}

	public Integer getRoleId() {
		return this.roleId;
	}

	public void setRoleId(Integer roleId) {
		this.roleId = roleId;
	}

	public String getRoleName() {
		return this.roleName;
	}

	public void setRoleName(String roleName) {
		this.roleName = roleName;
	}

	public Set<TblUser> getTblUserRoles() {
		return this.tblUserRoles;
	}

	public void setTblUserRoles(Set<TblUser> tblUserRoles) {
		this.tblUserRoles = tblUserRoles;
	}

}
